#######################
# Theme Customization #
#######################

title: Avinash                             # used in <title> tag & site header
author: Avinash Saxena                       # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Am a coder, am an innovator. I love to develop software to solve real world business problems
slogan: Welcome                         # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://avinsaxe.github.io             # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/avinsaxe
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    url: /html_pages/contact.html
    icon: /i/icons.svg#github
    outbound: true


  - name: CV
    url: /html_pages/cv.html
    icon: /i/icons.svg#github
    outbound: true



# Objects listed here will appear on the /projects.html page.
projects:
  - title: Managed File Transfer
    teaser: Extract mathematical expressions from text, using novel approaches of string matching, identifying syntactical structures of mathematical sentences, etc
    url: html_pages/mft.html
    role: Software Developer
    category: Oracle India

  - title: FashioNxt
    teaser: A responsive website for Fashion industry. Ruby on rails website, with features to create, update, delete, and search profiles for fashion professionals
    url: https://github.com/avinsaxe/match-my-fashion-public
    role: Full Stack Developer
    category: Web-Development

  - title: Barclays Capital
    teaser: Information Retrieval and Extraction tool. Web parsing and alert messaging
    url: html_pages/barclays.html
    role: Software Developer Intern
    category: Barclays Capital India

  - title: NLP Expression Extraction
    teaser: Extract mathematical expressions from text, using novel approaches of string matching, identifying syntactical structures of mathematical sentences, etc
    url: https://github.com/avinsaxe/derive_mathematical_expressions_from_text_nlp
    role: Algorithm design/development
    category: NLP

  - title: Distributed Systems
    teaser: Published a manuscript titled ‘Degradation analysis of probabilistic choice systems’ in IJRQSE
    url: html_pages/iiit.html
    role: Research Intern
    category: Distributed Systems/Fault Tolerance


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
